### ISSUE TITLE
师傅有考虑 新增加探测域名端口服务指纹吗，现在只能探测ip端口

### ISSUE THREAD

**Issue by cqrlhz** [Young873/xnmap#2]
师傅有考虑 新增加探测域名端口服务指纹吗，现在只能探测ip端口

**Comment by Young873** [comment]
是网站的指纹识别嘛？这个工具主要是做端口的服务识别的，会添加一部分HTTP协议下的重点指纹。如果要精准的web识别，还是用专门的web指纹识别工具比较好。
